
18_b4_30_34_f2_bd:
  hide_if_away: false
  icon:
  mac: 18:B4:30:34:F2:BD
  name: 18 b4 30 34 f2 bd
  picture:
  track: true

18_b4_30_33_3f_52:
  hide_if_away: false
  icon:
  mac: 18:B4:30:33:3F:52
  name: 18 b4 30 33 3f 52
  picture:
  track: true

johns_s10:
  hide_if_away: false
  icon:
  mac: 10:98:C3:A5:FC:1B
  name: Johns-S10
  picture:
  track: true

ringpro_cf:
  hide_if_away: false
  icon:
  mac: 3C:E1:A1:5E:AB:CF
  name: RingPro-cf
  picture:
  track: true

amazon_a32032653:
  hide_if_away: false
  icon:
  mac: 4C:EF:C0:AD:6E:EA
  name: amazon-a32032653
  picture:
  track: true

amazon_8fa754080:
  hide_if_away: false
  icon:
  mac: FC:49:2D:F3:99:B5
  name: amazon-8fa754080
  picture:
  track: true

tap_6174005g:
  hide_if_away: false
  icon:
  mac: F0:27:2D:A1:FD:20
  name: Tap-6174005G
  picture:
  track: true

3c_28_6d_fb_c2_d6:
  hide_if_away: false
  icon:
  mac: 3C:28:6D:FB:C2:D6
  name: Zacks-Pixel
  picture:
  track: true

amazon_864cb85c4:
  hide_if_away: false
  icon:
  mac: 00:71:47:D6:A9:26
  name: amazon-864cb85c4
  picture:
  track: true

holly_laptop:
  hide_if_away: false
  icon:
  mac: A0:A8:CD:94:97:42
  name: Holly-Laptop
  picture:
  track: true

f0_27_2d_c0_83_1f:
  hide_if_away: false
  icon:
  mac: F0:27:2D:C0:83:1F
  name: f0 27 2d c0 83 1f
  picture:
  track: true

abb1000:
  hide_if_away: false
  icon:
  mac: 78:D2:94:A7:5C:5B
  name: ABB1000
  picture:
  track: true

94_44_44_0d_6c_51:
  hide_if_away: false
  icon:
  mac: 94:44:44:0D:6C:51
  name: 94 44 44 0d 6c 51
  picture:
  track: true

amazon_4868735fb:
  hide_if_away: false
  icon:
  mac: 6C:56:97:6E:CC:56
  name: amazon-4868735fb
  picture:
  track: true

80_a5_89_db_65_f7:
  hide_if_away: false
  icon:
  mac: 80:A5:89:DB:65:F7
  name: 80 a5 89 db 65 f7
  picture:
  track: true

c0_97_27_05_58_6c:
  hide_if_away: false
  icon:
  mac: C0:97:27:05:58:6C
  name: c0 97 27 05 58 6c
  picture:
  track: true

amazon_22ec9726d:
  hide_if_away: false
  icon:
  mac: 00:FC:8B:44:52:0E
  name: amazon-22ec9726d
  picture:
  track: true

amazon_670ec4485:
  hide_if_away: false
  icon:
  mac: 08:A6:BC:D6:92:42
  name: amazon-670ec4485
  picture:
  track: true

amazon_8f40f2283:
  hide_if_away: false
  icon:
  mac: C4:95:00:71:0C:CC
  name: amazon-8f40f2283
  picture:
  track: true

hp3a6126:
  hide_if_away: false
  icon:
  mac: 24:BE:05:3A:61:26
  name: HP3A6126
  picture:
  track: true

johns_mbp_5:
  hide_if_away: false
  icon:
  mac: 78:4F:43:9D:89:71
  name: Johns-MBP-5
  picture:
  track: true

09ab01ac1217012u:
  hide_if_away: false
  icon:
  mac: 18:B4:30:C0:2B:71
  name: 09AB01AC1217012U
  picture:
  track: true

samsung:
  hide_if_away: false
  icon:
  mac: 64:1C:AE:63:AA:C6
  name: Samsung
  picture:
  track: true

hollys_s10:
  hide_if_away: false
  icon:
  mac: 10:98:C3:A3:26:39
  name: Hollys-S10
  picture:
  track: true

lauras_ipad:
  hide_if_away: false
  icon:
  mac: B0:65:BD:80:D2:1C
  name: Lauras-iPad
  picture:
  track: true

amazon_d7b89f03e:
  hide_if_away: false
  icon:
  mac: 44:00:49:3E:AF:F6
  name: amazon-d7b89f03e
  picture:
  track: true

galaxy_tab_s2:
  hide_if_away: false
  icon:
  mac: 34:14:5F:FA:4D:D7
  name: Galaxy-Tab-S2
  picture:
  track: true

amazon_5879c14fe:
  hide_if_away: false
  icon:
  mac: 00:FC:8B:13:5A:5A
  name: amazon-5879c14fe
  picture:
  track: true

amazon_0100005bb:
  hide_if_away: false
  icon:
  mac: 50:F5:DA:9B:EA:78
  name: amazon-0100005bb
  picture:
  track: true

hpabe1eb:
  hide_if_away: false
  icon:
  mac: B0:0C:D1:AB:E1:EB
  name: HPABE1EB
  picture:
  track: true

f4_b5_2f_a2_e0_ce:
  hide_if_away: false
  icon:
  mac: F4:B5:2F:A2:E0:CE
  name: f4 b5 2f a2 e0 ce
  picture:
  track: true

b8_bb_af_f4_a2_9f:
  hide_if_away: false
  icon:
  mac: B8:BB:AF:F4:A2:9F
  name: b8 bb af f4 a2 9f
  picture:
  track: true

hubv2_d052a8a050680001:
  hide_if_away: false
  icon:
  mac: D0:52:A8:A0:4E:C6
  name: hubv2-d052a8a050680001
  picture:
  track: true

vmb4000:
  hide_if_away: false
  icon:
  mac: 9C:3D:CF:0D:4D:8B
  name: VMB4000
  picture:
  track: true

hassio:
  hide_if_away: false
  icon:
  mac: DC:A6:32:09:74:66
  name: hassio
  picture:
  track: true

directv_hr22_dff86781:
  hide_if_away: false
  icon:
  mac: 00:19:DF:F8:67:81
  name: DIRECTV-HR22-DFF86781
  picture:
  track: true

directv_hr54_8c036e87:
  hide_if_away: false
  icon:
  mac: 2C:08:8C:03:6E:85
  name: DIRECTV-HR54-8C036E87
  picture:
  track: true

04_d4_c4_37_63_80:
  hide_if_away: false
  icon:
  mac: 04:D4:C4:37:63:80
  name: 04 d4 c4 37 63 80
  picture:
  track: true

00_a0_de_d9_3e_b2:
  hide_if_away: false
  icon:
  mac: 00:A0:DE:D9:3E:B2
  name: 00 a0 de d9 3e b2
  picture:
  track: true

mikrotik:
  hide_if_away: false
  icon:
  mac: 64:D1:54:33:AC:FE
  name: MikroTik
  picture:
  track: true

cisco00490:
  hide_if_away: false
  icon:
  mac: 60:02:B4:F1:D3:CE
  name: Cisco00490
  picture:
  track: true

5c_52_1e_9c_fd_10:
  hide_if_away: false
  icon:
  mac: 5C:52:1E:9C:FD:10
  name: 5c 52 1e 9c fd 10
  picture:
  track: true

johns_mbp_5_2:
  hide_if_away: false
  icon:
  mac: 48:65:EE:11:71:0A
  name: Johns-MBP-5
  picture:
  track: true
