# Morse, Lynnwood home, media player defintions
  - platform: yamaha
    host: 192.168.1.254
    name: "Yamaha Amp"
    source_names:
      HDMI1: "BD Player"
      HDMI2: "Set Top Box"
      HDMI3: "DIRECTV GENIE"
      HDMI4: "Fire TV Cube"
    zone_names:
      Main_Zone: "Family Room"      
# Samsung 65" 9 Series in Master Bedroom
  - platform: samsungtv
    host: 192.168.1.53
    port: 8001
    mac: C0:97:27:05:58:6C
    name: "Bedroom TV"
# Samsung Q8 Series (75)
  - platform: samsungtv
    host: 192.168.1.66
    port: 8001
    mac: 64:1C:AE:63:AA:C6
    name: "Family Room TV"
