
This does not work...

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

http:
  server_port: 8123
  base_url: https://morsehousehassio.local
  
  
  
secrets.yaml

# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/

logger: debug

http_password: Wg99Ml66HomeAssist
http_my_url: https:\\morse.family.home.assistant
arlo_username: john@morse-family.org
arlo_password: Wg99Ml66Arlo

# switch: !include config/switches.yaml

media_player: !include config/media_players.yaml

arlo:
  username: john@morse-family.org
  password: Wg99Ml66Arlo


From https://github.com/smarthomeuni/homeassistant-config

# Config

switch: !include config/switches.yaml
sensor: !include config/sensors.yaml
binary_sensor: !include config/binary_sensors.yaml
